/*
  Copyright (c) 2014-2015 Arduino LLC.  All right reserved.

  This library is free software; you can redistribute it and/or
  modify it under the terms of the GNU Lesser General Public
  License as published by the Free Software Foundation; either
  version 2.1 of the License, or (at your option) any later version.

  This library is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
  See the GNU Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public
  License along with this library; if not, write to the Free Software
  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
*/

#include "variant.h"

/*
 * Pins descriptions
 */

//TCC0 IOSET 6
//TCC1 IOSET 1
//TC0 IOSET 1
//TC1 IOSET 1
//TC2 IOSET 2
//TC3 IOSET 1
//TC4 IOSET 1
const PinDescription g_APinDescription[]=
{
  // 0..12 - Digital pins
  // ----------------------
  { PORTB, 15, PIO_DIGITAL, (PIN_ATTR_PWM_G|PIN_ATTR_DIGITAL|PIN_ATTR_TIMER|PIN_ATTR_EXTINT), No_ADC_Channel, TCC0_CH3, TC5_CH1, EXTERNAL_INT_15 }, //D0
  { PORTB, 14, PIO_DIGITAL, (PIN_ATTR_PWM_G|PIN_ATTR_DIGITAL|PIN_ATTR_TIMER|PIN_ATTR_EXTINT), No_ADC_Channel, TCC0_CH2, TC5_CH0, EXTERNAL_INT_14 }, // D1
  { PORTB, 11, PIO_DIGITAL, (PIN_ATTR_PWM_G|PIN_ATTR_DIGITAL|PIN_ATTR_TIMER|PIN_ATTR_EXTINT), No_ADC_Channel, TCC1_CH0, TCC0_CH5, EXTERNAL_INT_11 }, // D2
  { PORTB, 10, PIO_DIGITAL, (PIN_ATTR_PWM_F|PIN_ATTR_DIGITAL|PIN_ATTR_EXTINT), No_ADC_Channel, TCC0_CH4, NOT_ON_TIMER, EXTERNAL_INT_10 }, // D3
  { PORTA, 11, PIO_DIGITAL, (PIN_ATTR_PWM_G|PIN_ATTR_DIGITAL|PIN_ATTR_TIMER|PIN_ATTR_EXTINT), No_ADC_Channel, TCC1_CH7, TC1_CH1, EXTERNAL_INT_11 }, // D4
  { PORTA, 10, PIO_DIGITAL, (PIN_ATTR_PWM_G|PIN_ATTR_DIGITAL|PIN_ATTR_TIMER|PIN_ATTR_EXTINT), No_ADC_Channel, TCC1_CH6, TC1_CH0, EXTERNAL_INT_10  }, // D5
  { PORTA, 9, PIO_DIGITAL, (PIN_ATTR_PWM_G|PIN_ATTR_DIGITAL|PIN_ATTR_TIMER|PIN_ATTR_EXTINT), No_ADC_Channel, TCC1_CH5, TC0_CH0, EXTERNAL_INT_9 }, // D6
  { PORTB, 7, PIO_DIGITAL, (PIN_ATTR_DIGITAL|PIN_ATTR_EXTINT), No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_7 }, // D7
  { PORTB, 6, PIO_DIGITAL, (PIN_ATTR_DIGITAL|PIN_ATTR_EXTINT), No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_6 }, // D8
  { PORTB, 30, PIO_DIGITAL, (PIN_ATTR_PWM_G|PIN_ATTR_DIGITAL|PIN_ATTR_TIMER|PIN_ATTR_EXTINT), No_ADC_Channel, TCC0_CH6, TCC4_CH0, EXTERNAL_INT_14 }, // D9
  { PORTA, 12, PIO_DIGITAL, (PIN_ATTR_PWM_G|PIN_ATTR_DIGITAL|PIN_ATTR_TIMER|PIN_ATTR_EXTINT), No_ADC_Channel, TCC1_CH2, TC2_CH0, EXTERNAL_INT_12 }, // D10 - INT_IMU
  { PORTA, 15, PIO_DIGITAL, (PIN_ATTR_PWM_G|PIN_ATTR_DIGITAL|PIN_ATTR_TIMER|PIN_ATTR_EXTINT), No_ADC_Channel, TCC1_CH3, TC3_CH1, EXTERNAL_INT_15 }, // D11 - SAT_POWER
  { PORTB, 0, PIO_DIGITAL, (PIN_ATTR_DIGITAL|PIN_ATTR_EXTINT), No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_0 }, // D12 - OVTEMP
  
  // 13 (LED)
  { PORTA,  8, PIO_DIGITAL, PIN_ATTR_DIGITAL, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_NONE }, // D13, Neopixel

  // 14..19 - Analog pins
  // --------------------
  { PORTA,  7, PIO_ANALOG, (PIN_ATTR_ANALOG|PIN_ATTR_PWM_E|PIN_ATTR_EXTINT), ADC_Channel7, TC1_CH1, NOT_ON_TIMER, EXTERNAL_INT_7 }, // A0
  { PORTA,  6, PIO_ANALOG, (PIN_ATTR_ANALOG|PIN_ATTR_PWM_E|PIN_ATTR_EXTINT), ADC_Channel6, TC1_CH0, NOT_ON_TIMER, EXTERNAL_INT_6 }, // A1
  { PORTA,  5, PIO_ANALOG, (PIN_ATTR_ANALOG|PIN_ATTR_PWM_E|PIN_ATTR_EXTINT), ADC_Channel5, TC0_CH1, NOT_ON_TIMER, EXTERNAL_INT_5 }, // A2
  { PORTA,  4, PIO_ANALOG, (PIN_ATTR_ANALOG|PIN_ATTR_PWM_E|PIN_ATTR_EXTINT), ADC_Channel4, TC0_CH0, NOT_ON_TIMER, EXTERNAL_INT_4 }, // A3
  { PORTB,  9, PIO_ANALOG, (PIN_ATTR_ANALOG|PIN_ATTR_PWM_E|PIN_ATTR_EXTINT), ADC_Channel3, TC4_CH1, NOT_ON_TIMER, EXTERNAL_INT_9 }, // A4
  { PORTB,  8, PIO_ANALOG, (PIN_ATTR_ANALOG|PIN_ATTR_PWM_E|PIN_ATTR_EXTINT), ADC_Channel2, TC4_CH0, NOT_ON_TIMER, EXTERNAL_INT_8 }, // A5

  // 20..21 I2C pins (SDA/SCL)
  // ----------------------
  { PORTB, 12, PIO_SERCOM, PIN_ATTR_DIGITAL, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_12 }, // SDA: SERCOM4/PAD[0]
  { PORTB, 13, PIO_SERCOM, PIN_ATTR_DIGITAL, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_13 }, // SCL: SERCOM4/PAD[1]

  // 22..24 - SPI pins (SDI,SDO,SCK)
  // ----------------------
  { PORTB, 1, PIO_SERCOM_ALT, PIN_ATTR_DIGITAL, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_1 }, // SDI: SERCOM5/PAD[3]
  { PORTB, 2, PIO_SERCOM_ALT, PIN_ATTR_DIGITAL, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_2 }, // SDO: SERCOM5/PAD[0]
  { PORTB, 3, PIO_SERCOM_ALT, PIN_ATTR_DIGITAL, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_3 }, // SCK: SERCOM5/PAD[1]

  // 25..27 - USB
  // --------------------
  { NOT_A_PORT, 0, PIO_NOT_A_PIN, PIN_ATTR_NONE, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_NONE }, // USB Host enable DOES NOT EXIST ON THIS BOARD
  { PORTA, 24, PIO_COM, PIN_ATTR_NONE, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_NONE }, // USB/DM
  { PORTA, 27, PIO_COM, PIN_ATTR_NONE, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_NONE }, // USB/DP

  // 28 (AREF)
  { PORTA, 3, PIO_ANALOG, PIN_ATTR_ANALOG, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_NONE }, // VREF

  // ----------------------
  // 29 - Alternate use of A2 (DAC output)
  { PORTA,  5, PIO_ANALOG, PIN_ATTR_ANALOG, DAC_Channel1, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_NONE }, // DAC/VOUT1

  // ----------------------
  // 30..31 - TX/RX
  { PORTA, 22, PIO_SERCOM, (PIN_ATTR_DIGITAL|PIN_ATTR_PWM_F|PIN_ATTR_TIMER), No_ADC_Channel, TCC1_CH6, TCC0_CH2, EXTERNAL_INT_6 },  // TX: SERCOM3/PAD[0]
  { PORTA, 23, PIO_SERCOM, (PIN_ATTR_DIGITAL|PIN_ATTR_PWM_F|PIN_ATTR_TIMER), No_ADC_Channel, TCC1_CH7, TCC0_CH3, EXTERNAL_INT_7 }, // RX: SERCOM3/PAD[1]

  // ----------------------
  // 32..33 - SWDCLK/SWDIO D32/D33
  { PORTA, 30, PIO_DIGITAL, (PIN_ATTR_DIGITAL|PIN_ATTR_PWM_F|PIN_ATTR_TIMER), No_ADC_Channel, TCC2_CH0, TC6_CH0, EXTERNAL_INT_14 },  // D32
  { PORTA, 31, PIO_DIGITAL, (PIN_ATTR_DIGITAL|PIN_ATTR_PWM_F|PIN_ATTR_TIMER), No_ADC_Channel, TCC2_CH1, TC6_CH1, EXTERNAL_INT_15 }, // D33

  // ----------------------
  // 34..37 - SPI Flash
  { PORTA, 18, PIO_SERCOM, PIN_ATTR_NONE, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_NONE }, // SDI: SERCOM1/PAD[2]
  { PORTA, 16, PIO_SERCOM, PIN_ATTR_NONE, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_NONE }, // SDO: SERCOM1/PAD[0]
  { PORTA, 17, PIO_SERCOM, PIN_ATTR_NONE, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_NONE }, // SCK: SERCOM1/PAD[1]
  { PORTA, 19, PIO_DIGITAL, PIN_ATTR_DIGITAL, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_3 }, // CS
  
  // ----------------------
  // 38 - CS for SD card
  { PORTB, 22, PIO_DIGITAL, (PIN_ATTR_DIGITAL|PIN_ATTR_EXTINT), No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_6 }, // D38 - SD_CS

} ;

const void* g_apTCInstances[TCC_INST_NUM+TC_INST_NUM]={ TCC0, TCC1, TCC2, TCC3, TCC4, TC0, TC1, TC2, TC3, TC4, TC5 } ;
const uint32_t GCLK_CLKCTRL_IDs[TCC_INST_NUM+TC_INST_NUM] = { TCC0_GCLK_ID, TCC1_GCLK_ID, TCC2_GCLK_ID, TCC3_GCLK_ID, TCC4_GCLK_ID, TC0_GCLK_ID, TC1_GCLK_ID, TC2_GCLK_ID, TC3_GCLK_ID, TC4_GCLK_ID, TC5_GCLK_ID } ;

// Multi-serial objects instantiation
SERCOM sercom0( SERCOM0 ) ;
SERCOM sercom1( SERCOM1 ) ;
SERCOM sercom2( SERCOM2 ) ;
SERCOM sercom3( SERCOM3 ) ;
SERCOM sercom4( SERCOM4 ) ;
SERCOM sercom5( SERCOM5 ) ;

Uart Serial1( &sercom3, PIN_SERIAL1_RX, PIN_SERIAL1_TX, PAD_SERIAL1_RX, PAD_SERIAL1_TX ) ;

void SERCOM3_0_Handler()
{
  Serial1.IrqHandler();
}

void SERCOM3_1_Handler()
{
  Serial1.IrqHandler();
}

void SERCOM3_2_Handler()
{
  Serial1.IrqHandler();
}

void SERCOM3_3Handler()
{
  Serial1.IrqHandler();
}

void WIRE_IT_HANDLER(void) __attribute__ ((weak));